[sharepoint]
client_id = "TON_CLIENT_ID"
client_secret = "TON_CLIENT_SECRET"
site_url = "https://incendiebwbe.sharepoint.com/sites/PAU"
fichier_sharepoint = "/sites/PAU/Documents partages/Prévision/PowerBI/dispatch/DB rapport 2324.xlsx"
